title: Apple-Create-Install-Media
description: macOS App for creating a bootable volume of macOS.
github:
  repository_url: https://github.com/chris1111/Apple-Create-Install-Media
remote_theme: chris1111/cayman-dark
